name: myToken

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Frontend Environment Variable
      run: |
        echo "window.GITHUB_TOKEN = '${{ secrets.TUCHUANGTOKEN }}';" > $GITHUB_WORKSPACE/js/frontend-env.js
        echo "获取到的token ${{ secrets.TUCHUANGTOKEN }}"
      env:
        token: ${{ secrets.TUCHUANGTOKEN }}

    - name: Build and Deploy
      run: |
        # Build your frontend project here
        # No need to copy frontend-env.js
